### ISSUE TITLE
support config uri_param_names

### ISSUE THREAD

**Issue by imbooo** [yesinteractive/kong-jwt2header#3]
Can you support config uri_param_names parameter，this is very useful, thanks~

**Comment by cybrrnick** [comment]
Hello, currently the plugin looks for the token in the request authorization header. I will update to include support for query strings.  In the meantime, you could write  a serverless lua pre-function with Kong to transform the jwt in the querty string to a header so that this plugin can be used as is?

**Comment by imbooo** [comment]
Thank you very much. I'll try
